name: Build StatusLED (macOS & Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  macos:
    name: macOS app & DMG
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6 bleak

      - name: Build .app with PyInstaller (spec file)
        run: |
          if [ ! -f statusled_macos.spec ]; then
            echo "::error::File statusled_macos.spec not found. Add it to the repo root."
            exit 1
          fi
          pyinstaller statusled_macos.spec

      - name: Create DMG
        run: |
          hdiutil create -volname "StatusLED" -srcfolder "dist/StatusLED.app" -ov -format UDZO "StatusLED.dmg"

      - name: Zip .app (alternative artifact format)
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/StatusLED.app" "StatusLED.app.zip"

      # Optional signing+notarization (uncomment & set secrets)
      # - name: Import signing certs
      #   if: ${{ secrets.APPLE_CERT_P12_BASE64 != '' && secrets.APPLE_CERT_PASSWORD != '' }}
      #   uses: apple-actions/import-codesign-certs@v3
      #   with:
      #     p12-file-base64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
      #     p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}
      #
      # - name: Codesign app
      #   if: ${{ secrets.APPLE_CERT_P12_BASE64 != '' && secrets.APPLE_CERT_PASSWORD != '' && secrets.APPLE_IDENTITY != '' }}
      #   run: |
      #     codesign --force --deep --options runtime --sign "${{ secrets.APPLE_IDENTITY }}" "dist/StatusLED.app"
      #
      # - name: Notarize app
      #   if: ${{ secrets.APPLE_NOTARY_APPLE_ID != '' && secrets.APPLE_NOTARY_TEAM_ID != '' && secrets.APPLE_NOTARY_PASSWORD != '' }}
      #   run: |
      #     xcrun notarytool submit "dist/StatusLED.app"       #       --apple-id "${{ secrets.APPLE_NOTARY_APPLE_ID }}"       #       --password "${{ secrets.APPLE_NOTARY_PASSWORD }}"       #       --team-id "${{ secrets.APPLE_NOTARY_TEAM_ID }}" --wait
      #
      # - name: Staple ticket
      #   if: ${{ secrets.APPLE_NOTARY_APPLE_ID != '' && secrets.APPLE_NOTARY_TEAM_ID != '' && secrets.APPLE_NOTARY_PASSWORD != '' }}
      #   run: |
      #     xcrun stapler staple "dist/StatusLED.app"

      - uses: actions/upload-artifact@v4
        with:
          name: StatusLED-macOS
          path: |
            StatusLED.dmg
            StatusLED.app.zip

  windows:
    name: Windows exe (+ optional installer)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6 bleak

      - name: Build .exe with PyInstaller (spec file)
        run: |
          if not exist statusled_windows.spec (
            echo ::error::File statusled_windows.spec not found. Add it to the repo root.
            exit /b 1
          )
          pyinstaller statusled_windows.spec

      # Optional: build installer with Inno Setup action (uncomment when .iss present)
      # - name: Build Inno Setup installer
      #   uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      #   with:
      #     path: statusled_installer.iss
      #     options: /O+

      - uses: actions/upload-artifact@v4
        with:
          name: StatusLED-Windows
          path: |
            dist\StatusLED\**
            # If you built the installer, also upload:
            # StatusLED_Setup.exe
