name: Build StatusLED (macOS only)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  macos:
    name: macOS app & DMG
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6 bleak

      - name: Build .app with PyInstaller (spec file)
        run: |
          test -f statusled_macos.spec || { echo "::error::File statusled_macos.spec not found in repo root"; exit 1; }
          pyinstaller statusled_macos.spec

      - name: Create DMG
        run: |
          hdiutil create -volname "StatusLED" -srcfolder "dist/StatusLED.app" -ov -format UDZO "StatusLED.dmg"

      - name: Zip .app (alternative artifact format)
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/StatusLED.app" "StatusLED.app.zip"

      # Optional signing + notarization (uncomment and set secrets)
      # - name: Import signing certs
      #   uses: apple-actions/import-codesign-certs@v3
      #   with:
      #     p12-file-base64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
      #     p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}
      #
      # - name: Codesign app
      #   run: |
      #     codesign --force --deep --options runtime --sign "${{ secrets.APPLE_IDENTITY }}" "dist/StatusLED.app"
      #
      # - name: Notarize app
      #   run: |
      #     xcrun notarytool submit "dist/StatusLED.app" \
      #       --apple-id "${{ secrets.APPLE_NOTARY_APPLE_ID }}" \
      #       --password "${{ secrets.APPLE_NOTARY_PASSWORD }}" \
      #       --team-id "${{ secrets.APPLE_NOTARY_TEAM_ID }}" --wait
      #
      # - name: Staple ticket
      #   run: xcrun stapler staple "dist/StatusLED.app"

      - uses: actions/upload-artifact@v4
        with:
          name: StatusLED-macOS
        # Scaricherai questi due file dagli Artifacts
          path: |
            StatusLED.dmg
            StatusLED.app.zip
